<?php
include 'handlers/academic_handler.php';

?>

<div class="content">
    <nav class="main-header">
        <div class="col-lg-12 mt-3">
            <div class="col-12 mb-3">
                <h2 class="text-start"
                    style="font-size: 1.8rem; font-weight: bold; color: #4a4a4a; border-bottom: 2px solid #ccc; padding-bottom: 5px;">
                    Academic Year and Semester
                </h2>
            </div>
            <div class="card card-outline card-success">
                <div class="card-header">
                    <div class="card-tools">
                        <a class="btn btn-block btn-sm btn-default btn-flat border-success new_academic"
                            href="manage_academic.php">
                            <i class="fa fa-plus"></i> Add New
                        </a>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-8 col-md-4 ms-auto mt-3 mr-3">
                        <input type="text" id="searchInput" class="form-control form-control-sm"
                            placeholder="Search Academic Year">
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table tabe-hover table-bordered" id="list">
                            <colgroup>
                                <col width="5%">
                                <col width="25%">
                                <col width="25%">
                                <col width="15%">
                                <col width="15%">
                                <col width="15%">
                            </colgroup>
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Year</th>
                                    <th>Semester</th>
                                    <th>System Default</th>
                                    <th>Evaluation Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Table rows will be populated by the search and pagination AJAX -->
                            </tbody>
                        </table>
                        <p id="noRecordsMessage" style="display:none; color: black;" class="ml-1">No academic year
                            found.</p>
                    </div>
                </div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center" id="pagination-links">
                        <!-- Pagination links will be generated by the AJAX response -->
                    </ul>
                </nav>
            </div>
        </div>
    </nav>
</div>

<script>
    $(document).ready(function () {

        $(document).on('submit', '.delete-form', function (e) {
            e.preventDefault();
            var form = this;

            Swal.fire({
                title: 'Are you sure?',
                text: 'This action will permanently delete the academic year.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#28a745',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: 'POST',
                        url: 'academic_list.php', // Adjust the URL as needed
                        data: $(form).serialize(),
                        success: function () {
                            Swal.fire({
                                icon: 'success',
                                title: 'Deleted!',
                                text: 'Academic year has been deleted.',
                                showConfirmButton: false,
                                timer: 2000
                            }).then(() => {
                                window.location.href = 'academic_list.php'; // Adjust the redirect URL if needed
                            });
                        },
                        error: function () {
                            Swal.fire({
                                icon: 'error',
                                title: 'Oops...',
                                text: 'Failed to delete the academic year!',
                            });
                        }
                    });
                }
            });
        });
    });
</script>
<script>
    $(document).ready(function () {
        function updateTable(page = 1, search = '') {
            $.ajax({
                url: 'search_academic.php',
                method: 'POST',
                data: {
                    search: search,
                    page: page
                },
                success: function (response) {
                    var result = response.split('<!--pagination-->');

                    // Update the table body
                    $('#list tbody').html(result[0]);

                    // Update pagination only if available
                    if (result.length > 1) {
                        $('#pagination-links').html(result[1]);
                    }
                },
                error: function () {
                    console.error('Failed to fetch search results.');
                }
            });
        }

        // Live search
        $('#searchInput').on('keyup', function () {
            let searchValue = $(this).val().trim();

            // If user types #6, remove the # before sending the request
            if (searchValue.startsWith('#')) {
                searchValue = searchValue.substring(1);
            }

            updateTable(1, searchValue);
        });


        // Handle pagination clicks
        $(document).on('click', '.pagination a', function (e) {
            e.preventDefault();
            let pageNumber = $(this).data('page');
            updateTable(pageNumber, $('#searchInput').val());
        });

        // Load table data on page load
        updateTable(1);
    });
</script>
<style>
    .list-group-item:hover {
        color: black !important;
        font-weight: 700 !important;
    }

    .content .main-header {
        max-height: 90vh;
        overflow-y: auto;
        scroll-behavior: smooth;
    }

    .pagination a {
        cursor: pointer;
    }
</style>
<script>
    $(document).on('click', '.update_status', function () {
        var academicId = $(this).data('id');
        var newStatus = $(this).data('status');
        var statusText = newStatus === 1 ? 'Start Evaluation' : 'Close Evaluation';

        Swal.fire({
            title: statusText + '?',
            text: newStatus === 1 ?
                'This will start the evaluation period and assign the current semester.' :
                'This will close the evaluation period. Data will remain stored.',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#28a745',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: 'POST',
                    url: 'academic_list.php',
                    data: {
                        update_status: true,
                        academic_id: academicId,
                        status: newStatus
                    },
                    success: function () {
                        Swal.fire({
                            icon: 'success',
                            title: 'Status Updated!',
                            text: `The academic year is now ${newStatus === 1 ? 'active' : 'closed'}.`,
                            showConfirmButton: false,
                            timer: 2000
                        }).then(() => {
                            window.location.reload();
                        });
                    },
                    error: function () {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error!',
                            text: 'Failed to update the status. Please try again.',
                        });
                    }
                });
            }
        });
    });
</script>