<?php
include "handlers/questionnaire_handler.php";

?>

<div class="content">
    <nav class="main-header">
        <div class="col-lg-12 mt-3">
            <div class="col-12 mb-3">
                <h2 class="text-start"
                    style="font-size: 1.8rem; font-weight: bold; color: #4a4a4a; border-bottom: 2px solid #ccc; padding-bottom: 5px;">
                    Manage Questionnaires</h2>
            </div>
            <div class="card card-outline card-success">
                <div class="card-header mt-4">
                    <!-- <div class="card-tools">
                    <a class="btn btn-block btn-sm btn-default btn-flat border-primary new_academic"
                        href="manage_questionnaire_academic.php"><i class="fa fa-plus"></i> Add New</a>
                </div> -->
                </div>
                <div class="row mb-3">
                    <div class="col-8 col-md-4 ms-auto mt-3 mr-3">
                        <input type="text" id="searchInput" class="form-control form-control-sm" placeholder="Search">
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered" id="list">
                            <colgroup>
                                <col width="5%">
                                <col width="35%">
                                <col width="15%">
                                <col width="15%">
                                <col width="15%">
                                <col width="15%">
                            </colgroup>
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Academic Year</th>
                                    <th>Semester</th>
                                    <th>Questions</th>
                                    <th>Answered</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Table rows will be populated by the search and pagination AJAX -->
                            </tbody>
                        </table>
                        <p id="noRecordsMessage" style="display:none; color: black;" class="ml-1">No records found.</p>
                    </div>
                </div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center" id="pagination-links">
                        <!-- Pagination links will be generated by the AJAX response -->
                    </ul>
                </nav>
            </div>
        </div>
    </nav>
</div>

<script>
   $(document).ready(function() {
    function updateTable(page = 1, search = '') {
        $.ajax({
            url: 'search_questionnaire.php',
            method: 'POST',
            data: {
                search: search,
                page: page
            },
            dataType: 'json', // Expect JSON response
            success: function(response) {
                $('#list tbody').html(response.tableData); // Update table rows
                $('#pagination-links').html(response.pagination); // Update pagination
            },
            error: function() {
                console.error('Failed to fetch search results.');
            }
        });
    }

    $('#searchInput').on('keyup', function() {
        updateTable(1, $(this).val());
    });

    $(document).on('click', '.pagination a', function(e) {
        e.preventDefault();
        updateTable($(this).data('page'), $('#searchInput').val());
    });

    updateTable(1);
});
</script>
<style>
    .list-group-item:hover {
        color: black !important;
        font-weight: 700 !important;
    }

    .content .main-header {
        max-height: 90vh;
        overflow-y: auto;
        scroll-behavior: smooth;
    }
</style>